DROP USER IF EXISTS 'admin'@'%';
CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'G15';

DROP SCHEMA IF EXISTS restapidb;
CREATE SCHEMA restapidb;

GRANT ALL ON restapidb.* TO 'admin'@'%';
FLUSH PRIVILEGES;