DROP USER IF EXISTS 'root'@'%';
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'root';

DROP SCHEMA IF EXISTS restapidb;
CREATE SCHEMA restapidb;

GRANT ALL ON restapidb.* TO 'root'@'%';
FLUSH PRIVILEGES;

